name: CI Orso Backend

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DB_HOST: 127.0.0.1
      DB_USER: root
      DB_PASS: root
      DB_NAME: orso_db

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: orso_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: pdo, pdo_mysql

    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install

    - name: Dump Autoload
      run: php composer.phar dump-autoload

    - name: Wait for MySQL
      run: sleep 10
    
    - name: Import Database
      run: |
        mysql -h $DB_HOST -u $DB_USER -p$DB_PASS $DB_NAME < database.sql
      
    - name: Run PHPUnit
      run: php vendor/bin/phpunit
